### ISSUE TITLE
Error: ECONRESET

### ISSUE THREAD

**Issue by flagg19** [alexkirsz/dispatch-proxy#32]
Hi,
I tried to use dispatch-proxy with qBittorrent, both configured to use socks4, the error is:

error socks
      Unsupported SOCKS version: 71

In other issues I've read that it's the error you get when proxy receives an http request, which should not considering qBittorrent is using socks4 (not http), anyway, if I try to set up a http proxy instead of a socks proxy (dispatch start --http) the error changes to:

Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

Any clue? I'm running windows 7 64 bit - dispach version 0.1.2

**Comment by fangproxy** [comment]
flagg19 I signed up here to ask you how did you do it? kindly can you tell me step by step how did you made it work with Deluge? Github doesn't have an option to send a message so if you could, can you email at fang_proxy@yahoo.com.
