### ISSUE TITLE
dispatch, error socks Unsupported SOCKS version 71, 80, 67

### ISSUE THREAD

**Issue by smed79** [alexkirsz/dispatch-proxy#43]
Hello,

```
dispatch-proxy 0.1.2
Node 0.12.2
Manjaro Linux 0.8.12 Ascella
```

After starting `dispatch` and config firefox to conect via localhost:1080 i have no inernet connection and i get these errors :

```
$ dispatch start
SOCKS server started on localhost:1080
Dispatching to addresses 192.168.1.123@1, 192.168.1.124@1
     error socks
           Unsupported SOCKS version: 71
     error socks
           Unsupported SOCKS version: 80
     error socks
           Unsupported SOCKS version: 71
     error socks
           Unsupported SOCKS version: 67
```

![dispatch firefox proxy config](http://u.cubeupload.com/SMed79/H8AnGh.png)

I missing something?

**Comment by Morhaus** [comment]
English version below.

Salut @SMed79,

Par défaut, `dispatch start` lance un proxy **SOCKS 5**, donc le seul champ à remplir est "Hôte SOCKS" et son port, tu peux laisser le reste vide.

Tu peux aussi lancer un proxy HTTP via `dispatch start --http`. Dans ce cas, le champ à remplir est "Proxy HTTP".

Sauf raison particulière, je te recommande d'utiliser le proxy SOCKS.

--- 

Hello @SMed79,

By default, `dispatch start` starts a **SOCKS 5** proxy, which means you need to only fill the "Hôte SOCKS" field and leave the others empty.

You can also start a HTTP proxy by running `dispatch start --http`. In that case, you should only fill the "Proxy HTTP" field.

I'd recommend using the SOCKS proxy unless you have a reason to prefer the HTTP one.

**Comment by SMed79** [comment]
Hi @Morhaus,
eth0: 192.168.1.123 = 256K
wlan0: 192.168.1.124 = 256K

```
$ dispatch list
lo
    127.0.0.1 (IPv4, internal)
    ::1 (IPv6, internal)

eth0
    192.168.1.123 (IPv4)
    fe80::221:97ff:fed9:43bc (IPv6)

wlan0
    192.168.1.124 (IPv4)
    fe80::20a:ebff:fe77:cfcd (IPv6)
```

I have start a HTTP proxy `dispatch start --http` and use wget via this proxy to test speed: 
```
$ dispatch start --httpHTTP server started on localhost:8080
Dispatching to addresses 192.168.1.123@1, 192.168.1.124@1
```
`$ wget -e use_proxy=on -e http_proxy=localhost:8080 http://speedtest.wdc01.softlayer.com/downloads/test10.zip -O /dev/null`

I do not know why i have ~256K and not ~512K download speed ?!

`/dev/null            57%[===========>          ]   6,31M   238KB/s  tps 17s`

Merci pour votre aide.

**Comment by Morhaus** [comment]
When using wget, you only create **one** connection to a remote host, which is dispatched to only one network interface, in your case either `wlan0` or `eth0`. If you try running two wget simultaneously, or if you use a download manager that supports multipart downloading, you should see the difference.

**Comment by SMed79** [comment]
Yes, i confirm network monitor see me download activity just from eth0. ![network monitor](http://i.imgur.com/tbvDLc6.png)

no change with running two wget simultaneously http://i.cubeupload.com/czBNWA.png
same with `axel` and 4 connections via proxy http://i.cubeupload.com/gkQmW8.png

Any idea?








![speedtest](http://www.speedtest.net/result/4275553188.png)

**Comment by Morhaus** [comment]
Run dispatch with the `--debug` flag (`dispatch start --debug`) and check that your connections are correctly being dispatched to different network interfaces.

Have you tried using wget with the SOCKS proxy?

There are a few issues on this repo from people that haven't managed to use two different network interfaces at the same time on Linux. You might have more luck looking up the solutions they've come up with.

**Comment by SMed79** [comment]
- **Terminal window 1**
```
$ dispatch start --debug
SOCKS server started on localhost:1080
Dispatching to addresses 192.168.1.123@1, 192.168.1.124@1
   request [59d53e] 208.43.102.250:80
  dispatch [59d53e] 192.168.1.123
   connect [59d53e] 208.43.102.250:80
   request [aa8146] 208.43.102.250:80
  dispatch [aa8146] 192.168.1.124
   connect [aa8146] 208.43.102.250:80
       end [aa8146] clientConnection
       end [59d53e] clientConnection
```

- **Terminal window 2**
```
$ tsocks wget http://speedtest.wdc01.softlayer.com/downloads/test10.zip -O /dev/null
--2015-04-19 02:09:51--  http://speedtest.wdc01.softlayer.com/downloads/test10.zip
Résolution de speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)… 208.43.102.250
Connexion à speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)|208.43.102.250|:80… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 11536384 (11M) [application/zip]
Sauvegarde en : « /dev/null »

/dev/null            40%[=======>              ]   4,44M   115KB/s  tps 49s
```

- **Terminal window 3**
```
$ tsocks wget http://speedtest.wdc01.softlayer.com/downloads/test10.zip -O /dev/null
--2015-04-19 02:09:52--  http://speedtest.wdc01.softlayer.com/downloads/test10.zip
Résolution de speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)… 208.43.102.250
Connexion à speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)|208.43.102.250|:80… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 11536384 (11M) [application/zip]
Sauvegarde en : « /dev/null »

/dev/null            33%[======>               ]   3,73M   147KB/s  tps 53s
```

I will try to check others issues maybe i find solutions come up with.
Thanks!

**Comment by SMed79** [comment]
Tested and workink !
* VirtualBox
* W!n XP
* Node.JS
* dispatch-proxy
* [IDMan](http://en.wikipedia.org/wiki/Internet_Download_Manager)

:video_camera: http://getwebb.org/d/EAYVhQIe

**Comment by twonky4** [comment]
The 67 is `C` for `CONNECT` and the 71 is `G` for `GET`. With your configuration firefox try to connect to a socks proxy with the http proxy protocol. The firefox configuration is wrong. The same port for socks and http proxy is invalid.

I think the issue can be closed.
