### ISSUE TITLE
how dispatcher proxy technically work ? channel bonding strategie ? channel bonding architecture?

### ISSUE THREAD

**Issue by ilyesilyes** [alexkirsz/dispatch-proxy#89]
how dispatcher proxy technically work ?
channel bonding strategie ? channel bonding architecture?

**Comment by rlindsberg** [comment]
It sends connections via multiple network links.

**Comment by ilyesilyes** [comment]
thank you, i mean how it dispatch the traffic on the links ? for example using Round Robin? using the Throughput of the links  ?

**Comment by Unknown78** [comment]
It still haven't answered the question.

Channel Bonding or Load Balancing?
Which one this software use? 

The readme isn't clear either
> use it in conjunction with a threaded download manager, effectively combining multiple connections' speed in single file downloads,

I tried it with download manager software, with only one connection/section/chunk, it won't give me extra speed. Only when the server support parallel connection, then this software will work.

From what I've experienced, this software seems to use Load Balancing algorithm. Is that correct?

**Comment by rlindsberg** [comment]
> I tried it with download manager software, with only one connection/section/chunk, it won't give me extra speed. Only when the server support parallel connection, then this software will work.

Exactly.



> From what I've experienced, this software seems to use Load Balancing algorithm and not supporting Channel Bonding algorithm. Is that correct?

I am not familiar with the terms. But this program does not aggregate traffic and send it through different physical links.

**Comment by Unknown78** [comment]
Then it should be written clearly in the readme that this software use Load Balancing and not Channel Bonding algorithm. It may confuse someone in the future, just like me.
