### ISSUE TITLE
usecase: unstable connection

### ISSUE THREAD

**Issue by Zauberfisch** [alexkirsz/dispatch-proxy#9]
My most important usecase for a software like this is unstable mobile connections:

imagine I am on the train, I have the following 3 connections available:
- train wifi
- mobile 3g that I share via wifi
- 3g stick on my notebook

now, as I am on the train, and constantly moving, crossing forests, tunnels, ...
all the connections become unstable.
however, in a tunnel, the train wifi might be still working because they have a source in the tunnel.
or far out the city, one mobile carrier might have a node, but the other carrier has not.

so, I need a software that does load balancing, but more importantly, makes the connection as stable as possible.

is this usecase covered already? if so, can you add it to the readme?
if not, is it a planed feature?

**Comment by rlindsberg** [comment]
Hello Zauberfisch and thanks for posting this. I travel a lot and the wifi on trains isn't stable at all. I personally think this feature request is a good use case and I will add it to the developing plan.
