### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by JonasPapen** [alexkirsz/dispatch-proxy#90]
Hey when I try to install it i get this error: 

C:\Windows\System32>npm install -g dispatch-proxy
npm http GET https://registry.npmjs.org/dispatch-proxy
npm http GET https://registry.npmjs.org/dispatch-proxy
npm http GET https://registry.npmjs.org/dispatch-proxy
npm ERR! Error: connect EADDRNOTAVAIL
npm ERR!     at errnoException (net.js:863:11)
npm ERR!     at connect (net.js:726:19)
npm ERR!     at net.js:804:9
npm ERR!     at asyncCallback (dns.js:68:16)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:121:9)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "E:\\Program Files\\nodejs\\\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "dispatch-proxy"
npm ERR! cwd C:\Windows\System32
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! syscall connect
npm ERR! code EADDRNOTAVAIL
npm ERR! errno EADDRNOTAVAIL
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Windows\System32\npm-debug.log
npm ERR! not ok code 0

What can I do to install it successfully?

**Comment by rlindsberg** [comment]
Hello, could you try updating node and npm to the latest stable versions?

**Comment by rlindsberg** [comment]
Closed due to inactivity.
