### ISSUE TITLE
Add 'restart "dispatch start" command every time encounters an error' option

### ISSUE THREAD

**Issue by Unknown78** [alexkirsz/dispatch-proxy#93]
In my case, it's often to see connection reset in the console log.

```
error [4d70af] clientConnection
           Error: read ECONNRESET
               at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
```

At first encounters, it may seems working normally, but gradually over time, the load balancing will stop working. The speedtest won't show the maximum potential and browser lags.

I'm unable to find the problem and why does it happened. My solution right now is to manually restart the program every time I'm encountering it.

There could be automatic but still harsh solution to be able restart the dispatch process every time it encounters a reset error.

I suggest to add 'restart "dispatch start" command every time encounters an error' option, perhaps it will be useful for experimental debug other than my case above.

**Comment by HoomanJCode** [comment]
run as administrator. if not fixed, check your firewall.

**Comment by kavehra** [comment]
How

**Comment by kavehra** [comment]
How we can add Restart dispatch Start like a loop ?
