### ISSUE TITLE
Dispatch Proxy Error After 2 3 Min

### ISSUE THREAD

**Issue by kavehra** [alexkirsz/dispatch-proxy#95]
Hello 
i use from dispatch start  its Work for 2 or 3 min and after 3 min only 1 internet Work and I get error
My Windows 10 1903 64 bit 
and i have one Wired and one Wife Connection
https://pasteboard.co/IKKSo3F.jpg
its work Very good For 2 min idk why i get error
Thanks

**Comment by Unknown78** [comment]
I've already issued that on #93. Especially when fatal crash happened. It haven't been added yet.

**Comment by rlindsberg** [comment]
It could be a good feature. However, the owner has disappeared so I cannot do anything about it.

closes #93
